### ISSUE TITLE
Reverse child-parent extraction fails on master-detail relationship

### ISSUE THREAD

**Issue by eranvaizel** [davidmreed/amaxa#47]
When extracting in reverse order, the import fails when trying to load a child of a master-parent relationship, where the field was defined reparenting not allowed.
Example: We have an object called Employee, which has child File records, tied in a master detail. The Employee__c field on the File object is defined as reparenting not allowed.
If I try to extract just a specific File using a specific Id, followed by extracting the parent Employee record (using extract: descendents: true - reverse import), the operation fails: "Employee__c is a dependent lookup, but not updateable".
I'm assuming this happens because the operation is reverse and that identifies as an update to the Employee__c field, not insert. Which isn't allowed when reparenting is disabled for the relationship. Is there any possible solution or workaround for this?

Thank you!

**Comment by davidmreed** [comment]
Unfortunately, this structure just won't work in a situation as you describe. To populate lookups in reverse order, Amaxa performs a separate Update step using the Bulk API,  which would fail in this situation because that lookup cannot be updated at all.

Those objects will only be loadable in direct order,  parent-first.
